pipeline{
    agent any
    stages{
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Stage1'){
            steps{
                echo "echo Stage1"
            }
        }
            stage('Stage2'){
            steps{
                echo "echo Stage2"
            }
        }

    }
}
